version: '3.8'
services:
  db-dev: 
    image: postgres:16
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
    depends_on:
      db-dev:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data-dev: